name: Shuangseqiu Data and Analysis - Merged and Consolidated Push (Sort by Filename Timestamp with Debug)

on:
  schedule:
    # 每天北京时间上午9点运行 (UTC+8，所以在UTC时间是1点)
    - cron: '0 1 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  daily_process:
    runs-on: ubuntu-latest
    env: # Set timezone for all steps in this job
      TZ: Asia/Shanghai

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data acquisition script
      run: python ssq_data_processor.py

    - name: Run analysis script
      run: python ssq_analyzer.py

    - name: Create fixed filename copy
      run: |
        # 找出最新的分析报告 (按文件名时间戳排序)
        latest_report=$(ls ssq_analysis_output_*.txt | sort -r | head -n 1)

        # 创建固定文件名副本
        cp "$latest_report" "latest_ssq_analysis.txt"
        echo "Created fixed filename copy: latest_ssq_analysis.txt"

    - name: Clean old reports - keep only latest 3 by filename timestamp (Debug)
      run: |
        echo "--- Debugging File Cleanup ---"
        echo "Current directory:"
        pwd
        echo "Listing all analysis reports before cleanup:"
        # 使用 find 代替 ls 以确保更可靠地查找文件，即使文件名有空格等特殊字符 (尽管此处文件名格式固定)
        # 并且可以更容易地获取完整路径
        find . -maxdepth 1 -name 'ssq_analysis_output_*.txt' | sort

        # 获取文件列表并计数
        # 同样使用 find 配合 while 循环处理文件列表
        file_list_cmd="find . -maxdepth 1 -name 'ssq_analysis_output_*.txt' | sort"
        
        # 计算文件总数
        count=$(eval "$file_list_cmd" | wc -l)
        echo "Total number of reports found: $count"
        
        delete_count=$((count - 3))
        echo "Number of reports to delete: $delete_count"

        if [ $delete_count -gt 0 ]; then
          echo "Calculating list of reports to delete (oldest $delete_count by filename timestamp):"
          # 获取要删除的文件列表 (最旧的 $delete_count 个文件，按文件名时间戳排序)
          delete_files=$(eval "$file_list_cmd" | head -n $delete_count)
          echo "Files to delete:"
          echo "$delete_files"
          
          echo "Deleting $delete_count old reports..."
          echo "$delete_files" | while read file; do
            if [ -f "$file" ]; then # 再次检查文件是否存在
              echo "Attempting to remove: $file"
              rm "$file"
              exit_status=$?
              if [ $exit_status -ne 0 ]; then
                echo "Error removing $file. Exit status: $exit_status"
              else
                echo "Successfully removed: $file"
              fi
            else
              echo "File not found, skipping removal: $file"
            fi
          done
          echo "Deletion process finished."
        else
          echo "No need to clean reports, have $count (≤3) reports."
        fi
        
        echo "Listing analysis reports after cleanup attempt:"
        find . -maxdepth 1 -name 'ssq_analysis_output_*.txt' | sort
        echo "--- End Debugging ---"


    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit updated files (CSV and Analysis Reports)
      run: |
        echo "--- Debugging Commit Step ---"
        echo "Files staged before commit:"
        git status --porcelain
        
        # 添加 shuangseqiu.csv
        git add shuangseqiu.csv
        # 添加保留的分析报告和固定文件名副本
        # 使用 find 来确保只添加当前目录下的文件
        find . -maxdepth 1 -name 'ssq_analysis_output_*.txt' -print0 | xargs -0 git add
        git add latest_ssq_analysis.txt

        echo "Files staged after add:"
        git status --porcelain
        
        # 提交更改，包括删除的旧报告 (Git 会自动处理已删除文件的暂存)
        git commit -m "Auto update: Data and Analysis results $(date +'%Y-%m-%d')" || echo "No changes to commit"
        echo "--- End Debugging Commit Step ---"


    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
